<?php

namespace Database\Seeders;

use App\Models\Employee;
use App\Models\RfidCardMapping;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

/**
 * RfidCardMappingSeeder
 *
 * Assigns real physical RFID card UIDs to the first N employees (ordered by ID).
 * These employees are the ones with mock photos assigned by EmployeeFilipinoProfileSeeder.
 *
 * - If the employee already has an active mapping with a CARD-XXXX placeholder UID,
 *   it is replaced with the real card UID.
 * - If a mapping with the real UID already exists for that employee, it is left as-is
 *   (idempotent).
 * - Any other employee keeps whatever mapping was generated by RfidLedgerSeeder.
 *
 * Run standalone:
 *   php artisan db:seed --class=RfidCardMappingSeeder
 */
class RfidCardMappingSeeder extends Seeder
{
    /**
     * Real physical card UIDs mapped to employee slot index (0-based, ordered by employee ID).
     * Change the order or add more UIDs here as new physical cards arrive.
     */
    private const CARD_UIDS = [
        '1245140946',
        '1247268498',
        '1247241554',
        '1245028274',
        '1245263330',
        '1246222386',
        '1246091282',
        '1246545458',
        '1248120146',
        '1247241954',
    ];

    public function run(): void
    {
        $issuer    = User::first();
        $issuedAt  = Carbon::parse('2025-01-01');

        // Fetch exactly as many employees as we have card UIDs, ordered by ID
        // (same ordering used by EmployeeFilipinoProfileSeeder so the mapping
        //  lines up with the employees that have photos)
        $employees = Employee::orderBy('id')
            ->take(count(self::CARD_UIDS))
            ->get();

        if ($employees->isEmpty()) {
            $this->command->error('No employees found. Run EmployeeSeeder first.');
            return;
        }

        $this->command->info('RfidCardMappingSeeder: assigning ' . count(self::CARD_UIDS) . ' physical card UIDs...');

        foreach ($employees as $index => $employee) {
            $realUid = self::CARD_UIDS[$index];

            // Check if this exact UID is already assigned to this employee
            $exists = RfidCardMapping::where('employee_id', $employee->id)
                ->where('card_uid', $realUid)
                ->whereNull('deleted_at')
                ->exists();

            if ($exists) {
                $this->command->line("  SKIP  #{$employee->id} {$employee->employee_number} — UID {$realUid} already mapped");
                continue;
            }

            // Deactivate / soft-delete any existing active mapping for this employee
            // so the unique card_uid constraint is not violated
            RfidCardMapping::where('employee_id', $employee->id)
                ->where('is_active', true)
                ->whereNull('deleted_at')
                ->update([
                    'is_active'            => false,
                    'deactivated_at'       => now(),
                    'deactivation_reason'  => 'Replaced by physical card during seeding',
                ]);

            // Also deactivate any mapping that already holds this UID on another employee
            RfidCardMapping::where('card_uid', $realUid)
                ->whereNull('deleted_at')
                ->update([
                    'is_active'           => false,
                    'deactivated_at'      => now(),
                    'deactivation_reason' => 'UID reassigned during seeding',
                ]);

            // Create the real mapping
            RfidCardMapping::create([
                'card_uid'    => $realUid,
                'employee_id' => $employee->id,
                'card_type'   => 'mifare',
                'issued_at'   => $issuedAt,
                'issued_by'   => $issuer?->id,
                'is_active'   => true,
                'usage_count' => 0,
            ]);

            $profile  = $employee->profile;
            $name     = $profile
                ? "{$profile->first_name} {$profile->last_name}"
                : $employee->employee_number;

            $this->command->line("  OK    #{$employee->id} {$employee->employee_number} ({$name}) → {$realUid}");
        }

        $this->command->info('  Done.');
    }
}
