<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Asset Liability Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 9pt;
            color: #1f2937;
            margin: 0;
            padding: 15px;
        }
        .header {
            text-align: center;
            margin-bottom: 25px;
            border-bottom: 2px solid #dc2626;
            padding-bottom: 12px;
        }
        .header h1 {
            margin: 0;
            font-size: 18pt;
            color: #991b1b;
        }
        .meta-info {
            margin-bottom: 15px;
            padding: 8px;
            background-color: #f3f4f6;
            border-radius: 4px;
            font-size: 8pt;
        }
        .meta-info table {
            width: 100%;
        }
        .meta-info td {
            padding: 2px 5px;
        }
        .meta-info .label {
            font-weight: bold;
            width: 110px;
        }
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 10px;
            margin-bottom: 20px;
        }
        .stat-card {
            background: #f9fafb;
            border: 1px solid #e5e7eb;
            border-radius: 4px;
            padding: 10px;
            text-align: center;
        }
        .stat-card .value {
            font-size: 18pt;
            font-weight: bold;
            color: #991b1b;
            margin-bottom: 3px;
        }
        .stat-card .label {
            font-size: 8pt;
            color: #6b7280;
            text-transform: uppercase;
        }
        .alert-box {
            background-color: #fef2f2;
            border-left: 4px solid #dc2626;
            padding: 10px;
            margin-bottom: 15px;
        }
        .alert-box strong {
            color: #991b1b;
        }
        .section-title {
            font-size: 12pt;
            font-weight: bold;
            color: #991b1b;
            margin-top: 18px;
            margin-bottom: 8px;
            border-bottom: 1px solid #cbd5e1;
            padding-bottom: 4px;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }
        table.data-table th {
            background-color: #dc2626;
            color: white;
            padding: 6px;
            text-align: left;
            font-size: 8pt;
            font-weight: bold;
        }
        table.data-table td {
            padding: 5px 6px;
            border-bottom: 1px solid #e5e7eb;
            font-size: 8pt;
        }
        table.data-table tr:nth-child(even) {
            background-color: #f9fafb;
        }
        .status-badge {
            display: inline-block;
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 7pt;
            font-weight: bold;
        }
        .status-badge.not_returned {
            background-color: #fef3c7;
            color: #92400e;
        }
        .status-badge.overdue {
            background-color: #fee2e2;
            color: #991b1b;
        }
        .highlight-row {
            background-color: #fee2e2 !important;
        }
        .footer {
            margin-top: 25px;
            padding-top: 10px;
            border-top: 1px solid #cbd5e1;
            font-size: 7pt;
            color: #6b7280;
            text-align: center;
        }
        .summary-box {
            background: #fef2f2;
            border: 2px solid #dc2626;
            padding: 12px;
            margin-bottom: 20px;
            border-radius: 4px;
        }
        .summary-box h3 {
            margin: 0 0 10px 0;
            color: #991b1b;
            font-size: 11pt;
        }
        .summary-box .summary-value {
            font-size: 24pt;
            font-weight: bold;
            color: #991b1b;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Asset Liability Report</h1>
        <div class="subtitle" style="color: #6b7280; font-size: 10pt;">Unreturned Company Assets</div>
    </div>

    <div class="meta-info">
        <table>
            <tr>
                <td class="label">Report Date:</td>
                <td>{{ $generated_at->format('F d, Y h:i A') }}</td>
                <td class="label">Generated By:</td>
                <td>{{ $generated_by }}</td>
            </tr>
        </table>
    </div>

    <div class="summary-box">
        <h3>Total Outstanding Liability</h3>
        <div class="summary-value">₱ {{ number_format($stats['total_value'], 2) }}</div>
        <div style="margin-top: 8px; font-size: 9pt; color: #6b7280;">
            Across {{ $stats['total_assets'] }} unreturned assets 
            ({{ $stats['overdue_assets'] }} overdue, valued at ₱ {{ number_format($stats['overdue_value'], 2) }})
        </div>
    </div>

    @if($stats['overdue_assets'] > 0)
    <div class="alert-box">
        <strong>⚠ Critical:</strong> {{ $stats['overdue_assets'] }} assets are overdue for return, representing ₱ {{ number_format($stats['overdue_value'], 2) }} in liability.
    </div>
    @endif

    <div class="stats-grid">
        <div class="stat-card">
            <div class="value">{{ $stats['total_assets'] }}</div>
            <div class="label">Total Assets</div>
        </div>

        <div class="stat-card">
            <div class="value">{{ $stats['overdue_assets'] }}</div>
            <div class="label">Overdue</div>
        </div>

        <div class="stat-card">
            <div class="value">₱ {{ number_format($stats['total_value'], 0) }}</div>
            <div class="label">Total Value</div>
        </div>

        <div class="stat-card">
            <div class="value">₱ {{ number_format($stats['overdue_value'], 0) }}</div>
            <div class="label">Overdue Value</div>
        </div>
    </div>

    <h2 class="section-title">Unreturned Assets by Department</h2>
    <table class="data-table">
        <thead>
            <tr>
                <th>Department</th>
                <th style="text-align: right;">Asset Count</th>
                <th style="text-align: right;">Total Value</th>
            </tr>
        </thead>
        <tbody>
            @foreach($stats['by_department'] as $department => $deptStats)
                <tr>
                    <td>{{ $department }}</td>
                    <td style="text-align: right;">{{ $deptStats['count'] }}</td>
                    <td style="text-align: right;">₱ {{ number_format($deptStats['value'], 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <h2 class="section-title">Asset Type Distribution</h2>
    <table class="data-table">
        <thead>
            <tr>
                <th>Asset Type</th>
                <th style="text-align: right;">Count</th>
            </tr>
        </thead>
        <tbody>
            @foreach($stats['by_asset_type'] as $type => $count)
                <tr>
                    <td>{{ ucfirst(str_replace('_', ' ', $type)) }}</td>
                    <td style="text-align: right;">{{ $count }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <h2 class="section-title">Detailed Asset List</h2>
    @if($assets->count() > 0)
    <table class="data-table">
        <thead>
            <tr>
                <th>Employee</th>
                <th>Department</th>
                <th>Asset</th>
                <th>Type</th>
                <th style="text-align: right;">Value</th>
                <th>Expected Return</th>
                <th>Status</th>
                <th style="text-align: right;">Days Overdue</th>
            </tr>
        </thead>
        <tbody>
            @foreach($assets as $asset)
                @php
                    $isOverdue = $asset->return_status === 'overdue';
                    $daysOverdue = $isOverdue ? now()->diffInDays($asset->expected_return_date) : 0;
                @endphp
                <tr class="{{ $isOverdue ? 'highlight-row' : '' }}">
                    <td>
                        <strong>{{ $asset->offboardingCase->employee->profile?->first_name }} {{ $asset->offboardingCase->employee->profile?->last_name }}</strong><br>
                        <small style="color: #6b7280;">{{ $asset->offboardingCase->employee->employee_number }}</small>
                    </td>
                    <td>{{ $asset->offboardingCase->employee->department?->name ?? 'N/A' }}</td>
                    <td>{{ $asset->asset_name }}</td>
                    <td>{{ ucfirst(str_replace('_', ' ', $asset->asset_type)) }}</td>
                    <td style="text-align: right; font-weight: bold;">₱ {{ number_format($asset->asset_value, 2) }}</td>
                    <td>{{ $asset->expected_return_date?->format('M d, Y') }}</td>
                    <td>
                        <span class="status-badge {{ $asset->return_status }}">
                            {{ ucfirst(str_replace('_', ' ', $asset->return_status)) }}
                        </span>
                    </td>
                    <td style="text-align: center; color: {{ $daysOverdue > 0 ? '#dc2626' : '#6b7280' }}; font-weight: {{ $daysOverdue > 0 ? 'bold' : 'normal' }};">
                        {{ $daysOverdue > 0 ? $daysOverdue : '-' }}
                    </td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr style="background-color: #fee2e2; font-weight: bold;">
                <td colspan="4" style="text-align: right; padding: 8px;">TOTAL LIABILITY:</td>
                <td style="text-align: right; font-size: 10pt;">₱ {{ number_format($stats['total_value'], 2) }}</td>
                <td colspan="3"></td>
            </tr>
        </tfoot>
    </table>
    @else
    <p style="text-align: center; color: #16a34a; padding: 20px; font-weight: bold;">✓ No unreturned assets found. All assets have been returned.</p>
    @endif

    <div class="footer">
        <p>This is a computer-generated report from the HRIS Offboarding System.</p>
        <p>Asset Liability Report | Generated on {{ $generated_at->format('F d, Y \a\t h:i A') }}</p>
    </div>
</body>
</html>
