<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clearance Compliance Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 9pt;
            color: #1f2937;
            margin: 0;
            padding: 15px;
        }
        .header {
            text-align: center;
            margin-bottom: 25px;
            border-bottom: 2px solid #3b82f6;
            padding-bottom: 12px;
        }
        .header h1 {
            margin: 0;
            font-size: 18pt;
            color: #1e40af;
        }
        .meta-info {
            margin-bottom: 15px;
            padding: 8px;
            background-color: #f3f4f6;
            border-radius: 4px;
            font-size: 8pt;
        }
        .meta-info table {
            width: 100%;
        }
        .meta-info td {
            padding: 2px 5px;
        }
        .meta-info .label {
            font-weight: bold;
            width: 110px;
        }
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 10px;
            margin-bottom: 20px;
        }
        .stat-card {
            background: #f9fafb;
            border: 1px solid #e5e7eb;
            border-radius: 4px;
            padding: 10px;
            text-align: center;
        }
        .stat-card .value {
            font-size: 20pt;
            font-weight: bold;
            margin-bottom: 3px;
        }
        .stat-card .value.green {
            color: #16a34a;
        }
        .stat-card .value.red {
            color: #dc2626;
        }
        .stat-card .value.blue {
            color: #1e40af;
        }
        .stat-card .label {
            font-size: 8pt;
            color: #6b7280;
            text-transform: uppercase;
        }
        .section-title {
            font-size: 12pt;
            font-weight: bold;
            color: #1e40af;
            margin-top: 18px;
            margin-bottom: 8px;
            border-bottom: 1px solid #cbd5e1;
            padding-bottom: 4px;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }
        table.data-table th {
            background-color: #3b82f6;
            color: white;
            padding: 6px;
            text-align: left;
            font-size: 8pt;
            font-weight: bold;
        }
        table.data-table td {
            padding: 5px 6px;
            border-bottom: 1px solid #e5e7eb;
            font-size: 8pt;
        }
        table.data-table tr:nth-child(even) {
            background-color: #f9fafb;
        }
        .status-badge {
            display: inline-block;
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 7pt;
            font-weight: bold;
            text-transform: uppercase;
        }
        .status-badge.pending {
            background-color: #fef3c7;
            color: #92400e;
        }
        .status-badge.approved {
            background-color: #d1fae5;
            color: #065f46;
        }
        .status-badge.overdue {
            background-color: #fee2e2;
            color: #991b1b;
        }
        .alert-box {
            background-color: #fef2f2;
            border-left: 4px solid #dc2626;
            padding: 10px;
            margin-bottom: 15px;
        }
        .alert-box strong {
            color: #991b1b;
        }
        .footer {
            margin-top: 25px;
            padding-top: 10px;
            border-top: 1px solid #cbd5e1;
            font-size: 7pt;
            color: #6b7280;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Clearance Compliance Report</h1>
        <div class="subtitle">Active Offboarding Cases</div>
    </div>

    <div class="meta-info">
        <table>
            <tr>
                <td class="label">Report Date:</td>
                <td>{{ $generated_at->format('F d, Y h:i A') }}</td>
                <td class="label">Generated By:</td>
                <td>{{ $generated_by }}</td>
            </tr>
            @if($filter_status)
            <tr>
                <td class="label">Filter Applied:</td>
                <td colspan="3">Status: {{ ucfirst($filter_status) }}</td>
            </tr>
            @endif
        </table>
    </div>

    @if($stats['overdue'] > 0)
    <div class="alert-box">
        <strong>⚠ Attention Required:</strong> There are {{ $stats['overdue'] }} overdue clearance items that require immediate action.
    </div>
    @endif

    <div class="stats-section">
        <div class="stats-grid">
            <div class="stat-card">
                <div class="value blue">{{ $stats['total_items'] }}</div>
                <div class="label">Total Items</div>
            </div>

            <div class="stat-card">
                <div class="value green">{{ $stats['approved'] }}</div>
                <div class="label">Approved</div>
            </div>

            <div class="stat-card">
                <div class="value red">{{ $stats['pending'] }}</div>
                <div class="label">Pending</div>
            </div>

            <div class="stat-card">
                <div class="value red">{{ $stats['overdue'] }}</div>
                <div class="label">Overdue</div>
            </div>
        </div>

        <div style="text-align: center; margin-bottom: 15px;">
            <strong>Compliance Rate:</strong> 
            <span style="font-size: 16pt; color: {{ $stats['compliance_rate'] >= 80 ? '#16a34a' : '#dc2626' }};">
                {{ $stats['compliance_rate'] }}%
            </span>
        </div>
    </div>

    <h2 class="section-title">Clearance Items</h2>
    @if($clearance_items->count() > 0)
    <table class="data-table">
        <thead>
            <tr>
                <th>Case #</th>
                <th>Employee</th>
                <th>Department</th>
                <th>Clearance Item</th>
                <th>Assigned To</th>
                <th>Status</th>
                <th>Due Date</th>
                <th>Overdue Days</th>
            </tr>
        </thead>
        <tbody>
            @foreach($clearance_items as $item)
                @php
                    $isOverdue = $item->status === 'pending' && $item->due_date < now();
                    $daysOverdue = $isOverdue ? now()->diffInDays($item->due_date) : 0;
                @endphp
                <tr>
                    <td>{{ $item->offboardingCase->case_number }}</td>
                    <td>
                        <strong>{{ $item->offboardingCase->employee->profile?->first_name }} {{ $item->offboardingCase->employee->profile?->last_name }}</strong><br>
                        <small style="color: #6b7280;">{{ $item->offboardingCase->employee->employee_number }}</small>
                    </td>
                    <td>{{ $item->offboardingCase->employee->department?->name ?? 'N/A' }}</td>
                    <td>{{ $item->clearance_name }}</td>
                    <td>{{ $item->assignedTo?->name ?? 'Unassigned' }}</td>
                    <td>
                        <span class="status-badge {{ $isOverdue ? 'overdue' : $item->status }}">
                            {{ $isOverdue ? 'Overdue' : ucfirst($item->status) }}
                        </span>
                    </td>
                    <td>{{ $item->due_date->format('M d, Y') }}</td>
                    <td style="text-align: center; color: {{ $daysOverdue > 0 ? '#dc2626' : '#6b7280' }}; font-weight: {{ $daysOverdue > 0 ? 'bold' : 'normal' }};">
                        {{ $daysOverdue > 0 ? $daysOverdue : '-' }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <p style="text-align: center; color: #6b7280; padding: 20px;">No clearance items found matching the criteria.</p>
    @endif

    <h2 class="section-title">Department Summary</h2>
    <table class="data-table">
        <thead>
            <tr>
                <th>Department</th>
                <th style="text-align: right;">Active Items</th>
            </tr>
        </thead>
        <tbody>
            @foreach($stats['by_department'] as $department => $count)
                <tr>
                    <td>{{ $department }}</td>
                    <td style="text-align: right;">{{ $count }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This is a computer-generated report from the HRIS Offboarding System.</p>
        <p>Clearance Compliance Report | Generated on {{ $generated_at->format('F d, Y \a\t h:i A') }}</p>
    </div>
</body>
</html>
