<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Monthly Separation Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10pt;
            color: #1f2937;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #3b82f6;
            padding-bottom: 15px;
        }
        .header h1 {
            margin: 0;
            font-size: 20pt;
            color: #1e40af;
        }
        .header .subtitle {
            margin-top: 5px;
            font-size: 12pt;
            color: #6b7280;
        }
        .meta-info {
            margin-bottom: 20px;
            padding: 10px;
            background-color: #f3f4f6;
            border-radius: 4px;
        }
        .meta-info table {
            width: 100%;
        }
        .meta-info td {
            padding: 3px 5px;
        }
        .meta-info .label {
            font-weight: bold;
            width: 150px;
        }
        .stats-section {
            margin-bottom: 25px;
        }
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 15px;
            margin-bottom: 20px;
        }
        .stat-card {
            background: #f9fafb;
            border: 1px solid #e5e7eb;
            border-radius: 6px;
            padding: 12px;
            text-align: center;
        }
        .stat-card .value {
            font-size: 24pt;
            font-weight: bold;
            color: #1e40af;
            margin-bottom: 5px;
        }
        .stat-card .label {
            font-size: 9pt;
            color: #6b7280;
            text-transform: uppercase;
        }
        .stat-card .change {
            font-size: 8pt;
            margin-top: 5px;
        }
        .stat-card .change.positive {
            color: #dc2626;
        }
        .stat-card .change.negative {
            color: #16a34a;
        }
        .section-title {
            font-size: 14pt;
            font-weight: bold;
            color: #1e40af;
            margin-top: 20px;
            margin-bottom: 10px;
            border-bottom: 1px solid #cbd5e1;
            padding-bottom: 5px;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table.data-table th {
            background-color: #3b82f6;
            color: white;
            padding: 8px;
            text-align: left;
            font-size: 9pt;
            font-weight: bold;
        }
        table.data-table td {
            padding: 6px 8px;
            border-bottom: 1px solid #e5e7eb;
            font-size: 9pt;
        }
        table.data-table tr:hover {
            background-color: #f9fafb;
        }
        .badge {
            display: inline-block;
            padding: 2px 8px;
            border-radius: 3px;
            font-size: 8pt;
            font-weight: bold;
        }
        .badge.voluntary {
            background-color: #dbeafe;
            color: #1e40af;
        }
        .badge.involuntary {
            background-color: #fee2e2;
            color: #991b1b;
        }
        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 1px solid #cbd5e1;
            font-size: 8pt;
            color: #6b7280;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Monthly Separation Report</h1>
        <div class="subtitle">{{ $month->format('F Y') }}</div>
    </div>

    <div class="meta-info">
        <table>
            <tr>
                <td class="label">Report Date:</td>
                <td>{{ $generated_at->format('F d, Y h:i A') }}</td>
                <td class="label">Generated By:</td>
                <td>{{ $generated_by }}</td>
            </tr>
        </table>
    </div>

    <div class="stats-section">
        <div class="stats-grid">
            <div class="stat-card">
                <div class="value">{{ $stats['total_separations'] }}</div>
                <div class="label">Total Separations</div>
                @if($stats['change_percentage'] != 0)
                    <div class="change {{ $stats['change_percentage'] > 0 ? 'positive' : 'negative' }}">
                        {{ $stats['change_percentage'] > 0 ? '+' : '' }}{{ $stats['change_percentage'] }}% from previous month
                    </div>
                @endif
            </div>

            <div class="stat-card">
                <div class="value">{{ $stats['voluntary'] }}</div>
                <div class="label">Voluntary Separations</div>
            </div>

            <div class="stat-card">
                <div class="value">{{ $stats['involuntary'] }}</div>
                <div class="label">Involuntary Separations</div>
            </div>
        </div>
    </div>

    <h2 class="section-title">Separation Type Breakdown</h2>
    <table class="data-table">
        <thead>
            <tr>
                <th>Separation Type</th>
                <th style="text-align: right;">Count</th>
                <th style="text-align: right;">Percentage</th>
            </tr>
        </thead>
        <tbody>
            @foreach($stats['by_type'] as $type => $count)
                <tr>
                    <td>{{ ucfirst(str_replace('_', ' ', $type)) }}</td>
                    <td style="text-align: right;">{{ $count }}</td>
                    <td style="text-align: right;">{{ $stats['total_separations'] > 0 ? round(($count / $stats['total_separations']) * 100, 1) : 0 }}%</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <h2 class="section-title">Department Distribution</h2>
    <table class="data-table">
        <thead>
            <tr>
                <th>Department</th>
                <th style="text-align: right;">Count</th>
                <th style="text-align: right;">Percentage</th>
            </tr>
        </thead>
        <tbody>
            @foreach($stats['by_department'] as $department => $count)
                <tr>
                    <td>{{ $department }}</td>
                    <td style="text-align: right;">{{ $count }}</td>
                    <td style="text-align: right;">{{ $stats['total_separations'] > 0 ? round(($count / $stats['total_separations']) * 100, 1) : 0 }}%</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <h2 class="section-title">Detailed Separation List</h2>
    <table class="data-table">
        <thead>
            <tr>
                <th>Employee</th>
                <th>Department</th>
                <th>Position</th>
                <th>Separation Type</th>
                <th>Date</th>
                <th>Rehire</th>
            </tr>
        </thead>
        <tbody>
            @foreach($cases as $case)
                <tr>
                    <td>
                        <strong>{{ $case->employee->profile?->first_name }} {{ $case->employee->profile?->last_name }}</strong><br>
                        <small style="color: #6b7280;">{{ $case->employee->employee_number }}</small>
                    </td>
                    <td>{{ $case->employee->department?->name ?? 'N/A' }}</td>
                    <td>{{ $case->employee->position?->title ?? 'N/A' }}</td>
                    <td>
                        @php
                            $isVoluntary = in_array($case->separation_type, ['resignation', 'retirement']);
                        @endphp
                        <span class="badge {{ $isVoluntary ? 'voluntary' : 'involuntary' }}">
                            {{ ucfirst(str_replace('_', ' ', $case->separation_type)) }}
                        </span>
                    </td>
                    <td>{{ $case->actual_separation_date?->format('M d, Y') }}</td>
                    <td style="text-align: center;">{{ $case->rehire_eligible ? 'Yes' : 'No' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This is a computer-generated report from the HRIS Offboarding System.</p>
        <p>Generated on {{ $generated_at->format('F d, Y \a\t h:i A') }} by {{ $generated_by }}</p>
    </div>
</body>
</html>
