<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rehire Eligibility Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10pt;
            color: #1f2937;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #16a34a;
            padding-bottom: 15px;
        }
        .header h1 {
            margin: 0;
            font-size: 20pt;
            color: #15803d;
        }
        .header .subtitle {
            margin-top: 5px;
            font-size: 12pt;
            color: #6b7280;
        }
        .meta-info {
            margin-bottom: 20px;
            padding: 10px;
            background-color: #f3f4f6;
            border-radius: 4px;
        }
        .meta-info table {
            width: 100%;
        }
        .meta-info td {
            padding: 3px 5px;
        }
        .meta-info .label {
            font-weight: bold;
            width: 150px;
        }
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 15px;
            margin-bottom: 20px;
        }
        .stat-card {
            background: #f0fdf4;
            border: 1px solid #bbf7d0;
            border-radius: 6px;
            padding: 12px;
            text-align: center;
        }
        .stat-card .value {
            font-size: 24pt;
            font-weight: bold;
            color: #15803d;
            margin-bottom: 5px;
        }
        .stat-card .label {
            font-size: 9pt;
            color: #6b7280;
            text-transform: uppercase;
        }
        .section-title {
            font-size: 14pt;
            font-weight: bold;
            color: #15803d;
            margin-top: 20px;
            margin-bottom: 10px;
            border-bottom: 1px solid #cbd5e1;
            padding-bottom: 5px;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table.data-table th {
            background-color: #16a34a;
            color: white;
            padding: 8px;
            text-align: left;
            font-size: 9pt;
            font-weight: bold;
        }
        table.data-table td {
            padding: 6px 8px;
            border-bottom: 1px solid #e5e7eb;
            font-size: 9pt;
        }
        table.data-table tr:nth-child(even) {
            background-color: #f9fafb;
        }
        .badge {
            display: inline-block;
            padding: 2px 8px;
            border-radius: 3px;
            font-size: 8pt;
            font-weight: bold;
        }
        .badge.resignation {
            background-color: #dbeafe;
            color: #1e40af;
        }
        .badge.retirement {
            background-color: #e0e7ff;
            color: #4338ca;
        }
        .badge.other {
            background-color: #f3f4f6;
            color: #374151;
        }
        .info-box {
            background-color: #eff6ff;
            border-left: 4px solid #3b82f6;
            padding: 10px;
            margin-bottom: 15px;
            font-size: 9pt;
        }
        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 1px solid #cbd5e1;
            font-size: 8pt;
            color: #6b7280;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Rehire Eligibility Report</h1>
        <div class="subtitle">Former Employees Available for Rehire</div>
    </div>

    <div class="meta-info">
        <table>
            <tr>
                <td class="label">Report Date:</td>
                <td>{{ $generated_at->format('F d, Y h:i A') }}</td>
                <td class="label">Generated By:</td>
                <td>{{ $generated_by }}</td>
            </tr>
            <tr>
                <td class="label">Separation Period:</td>
                <td colspan="3">{{ $date_from->format('M d, Y') }} to {{ $date_to->format('M d, Y') }}</td>
            </tr>
        </table>
    </div>

    <div class="info-box">
        <strong>ℹ Purpose:</strong> This report identifies former employees who left the company in good standing and are eligible for rehire. 
        These individuals can be considered for future openings based on their previous performance and exit circumstances.
    </div>

    <div class="stats-section">
        <div class="stats-grid">
            <div class="stat-card">
                <div class="value">{{ $stats['total_eligible'] }}</div>
                <div class="label">Total Eligible</div>
            </div>

            <div class="stat-card">
                <div class="value">{{ $stats['with_high_performance'] }}</div>
                <div class="label">High Performers</div>
            </div>

            <div class="stat-card">
                <div class="value">
                    {{ $stats['total_eligible'] > 0 ? round(($stats['with_high_performance'] / $stats['total_eligible']) * 100) : 0 }}%
                </div>
                <div class="label">High Performer Rate</div>
            </div>
        </div>
    </div>

    <h2 class="section-title">Separation Type Breakdown</h2>
    <table class="data-table">
        <thead>
            <tr>
                <th>Separation Type</th>
                <th style="text-align: right;">Count</th>
                <th style="text-align: right;">Percentage</th>
            </tr>
        </thead>
        <tbody>
            @foreach($stats['by_separation_type'] as $type => $count)
                <tr>
                    <td>{{ ucfirst(str_replace('_', ' ', $type)) }}</td>
                    <td style="text-align: right;">{{ $count }}</td>
                    <td style="text-align: right;">{{ $stats['total_eligible'] > 0 ? round(($count / $stats['total_eligible']) * 100, 1) : 0 }}%</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <h2 class="section-title">Department Distribution</h2>
    <table class="data-table">
        <thead>
            <tr>
                <th>Department</th>
                <th style="text-align: right;">Eligible Candidates</th>
            </tr>
        </thead>
        <tbody>
            @foreach($stats['by_department'] as $department => $count)
                <tr>
                    <td>{{ $department }}</td>
                    <td style="text-align: right;">{{ $count }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <h2 class="section-title">Rehire-Eligible Former Employees</h2>
    @if($cases->count() > 0)
    <table class="data-table">
        <thead>
            <tr>
                <th>Employee Details</th>
                <th>Department</th>
                <th>Position</th>
                <th>Separation Type</th>
                <th>Separation Date</th>
                <th>Exit Score</th>
                <th>Eligibility Notes</th>
            </tr>
        </thead>
        <tbody>
            @foreach($cases as $case)
                @php
                    $exitScore = null;
                    if ($case->exitInterview) {
                        $exitScore = round(($case->exitInterview->work_environment_satisfaction +
                                           $case->exitInterview->management_satisfaction +
                                           $case->exitInterview->compensation_satisfaction +
                                           $case->exitInterview->career_growth_satisfaction +
                                           $case->exitInterview->work_life_balance_satisfaction) / 5, 1);
                    }
                @endphp
                <tr>
                    <td>
                        <strong>{{ $case->employee->profile?->first_name }} {{ $case->employee->profile?->last_name }}</strong><br>
                        <small style="color: #6b7280;">{{ $case->employee->employee_number }}</small>
                    </td>
                    <td>{{ $case->employee->department?->name ?? 'N/A' }}</td>
                    <td>{{ $case->employee->position?->title ?? 'N/A' }}</td>
                    <td>
                        <span class="badge {{ $case->separation_type }}">
                            {{ ucfirst(str_replace('_', ' ', $case->separation_type)) }}
                        </span>
                    </td>
                    <td>{{ $case->actual_separation_date?->format('M d, Y') }}</td>
                    <td style="text-align: center; {{ $exitScore && $exitScore >= 4 ? 'color: #16a34a; font-weight: bold;' : '' }}">
                        {{ $exitScore ?? 'N/A' }}
                    </td>
                    <td style="font-size: 8pt;">{{ $case->rehire_eligible_reason ?? 'Good standing' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <p style="text-align: center; color: #6b7280; padding: 20px;">No rehire-eligible employees found for the selected period.</p>
    @endif

    <div class="footer">
        <p>This is a computer-generated report from the HRIS Offboarding System.</p>
        <p>Rehire Eligibility Report | Generated on {{ $generated_at->format('F d, Y \a\t h:i A') }}</p>
        <p style="margin-top: 5px;">
            <strong>Note:</strong> Exit scores are averages from exit interviews (1-5 scale). Scores ≥4 indicate high performers.
        </p>
    </div>
</body>
</html>
