<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * This migration enhances the shift_assignments table with additional tracking columns
     * and indexes for better performance and audit trail support.
     *
     * Phase 4 Implementation: Enhancement & Documentation
     * Adds columns to track:
     *   - When a shift was generated (generated_at timestamp)
     *   - Who generated it (generated_by user FK)
     *   - Whether conflicts were detected and overridden (conflict_detected flag)
     *
     * Also adds performance indexes for common queries:
     *   - Finding shifts by assignment source
     *   - Finding conflicts by date
     *   - Querying shifts for employee on specific date
     */
    public function up(): void
    {
        Schema::table('shift_assignments', function (Blueprint $table) {
            // Add generated_at timestamp - tracks when shift was generated
            if (!Schema::hasColumn('shift_assignments', 'generated_at')) {
                $table->timestamp('generated_at')->nullable()->after('source_details')
                    ->comment('When this shift was generated by the system');
            }

            // Add generated_by FK - tracks who initiated the generation
            if (!Schema::hasColumn('shift_assignments', 'generated_by_user_id')) {
                $table->foreignId('generated_by_user_id')
                    ->nullable()
                    ->after('generated_at')
                    ->constrained('users', 'id')
                    ->onDelete('set null')
                    ->comment('User who initiated shift generation');
            }

            // Add conflict_detected flag - marks shifts generated despite conflicts
            if (!Schema::hasColumn('shift_assignments', 'conflict_detected')) {
                $table->boolean('conflict_detected')->default(false)->after('generated_by_user_id')
                    ->comment('Whether conflicts were detected and overridden');
            }

            // Add composite index for source filtering
            // Useful for queries like: "Show all shifts generated from rotation for employee X"
            $table->index(['assignment_source', 'employee_id'], 'idx_source_employee');

            // Add composite index for finding conflicts by date
            // Useful for: "Find all conflicted shifts in date range"
            $table->index(['conflict_detected', 'date'], 'idx_conflicts_date');

            // Add composite index for employee's shifts on specific date with all relations
            // Useful for: "Get employee's full shift data for a date"
            $table->index(['employee_id', 'date', 'rotation_assignment_id'], 'idx_employee_date_rotation');

            // Index on generated_by for audit queries
            $table->index('generated_by_user_id', 'idx_generated_by');

            // Index on generated_at for timeline queries
            $table->index('generated_at', 'idx_generated_at');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('shift_assignments', function (Blueprint $table) {
            // Drop indexes first
            $table->dropIndexIfExists('idx_source_employee');
            $table->dropIndexIfExists('idx_conflicts_date');
            $table->dropIndexIfExists('idx_employee_date_rotation');
            $table->dropIndexIfExists('idx_generated_by');
            $table->dropIndexIfExists('idx_generated_at');

            // Drop columns
            if (Schema::hasColumn('shift_assignments', 'conflict_detected')) {
                $table->dropColumn('conflict_detected');
            }
            if (Schema::hasColumn('shift_assignments', 'generated_by_user_id')) {
                $table->dropForeign(['generated_by_user_id']);
                $table->dropColumn('generated_by_user_id');
            }
            if (Schema::hasColumn('shift_assignments', 'generated_at')) {
                $table->dropColumn('generated_at');
            }
        });
    }
};
