"""add security tables for Phase 5

Revision ID: 180c8670682c
Revises: 9984172f74bd
Create Date: 2026-03-11 17:31:02.254809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '180c8670682c'
down_revision: Union[str, Sequence[str], None] = '9984172f74bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('security_audit_logs_created_at_index', table_name='security_audit_logs')
    op.drop_index('security_audit_logs_event_type_index', table_name='security_audit_logs')
    op.drop_index('security_audit_logs_severity_index', table_name='security_audit_logs')
    op.drop_index('security_audit_logs_user_id_index', table_name='security_audit_logs')
    op.drop_table('security_audit_logs')
    op.drop_table('failed_jobs')
    op.drop_index('timesheets_date_status_index', table_name='timesheets')
    op.drop_table('timesheets')
    op.drop_table('migrations')
    op.drop_table('permissions')
    op.drop_table('role_templates')
    op.drop_table('role_has_permissions')
    op.drop_index('application_uptime_logs_checked_at_index', table_name='application_uptime_logs')
    op.drop_index('application_uptime_logs_is_healthy_checked_at_index', table_name='application_uptime_logs')
    op.drop_table('application_uptime_logs')
    op.drop_table('cache')
    op.drop_index('model_has_permissions_model_id_model_type_index', table_name='model_has_permissions')
    op.drop_table('model_has_permissions')
    op.drop_table('users')
    op.drop_table('system_onboarding')
    op.drop_table('job_batches')
    op.drop_index('jobs_queue_index', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('enabled_next_run_idx', table_name='scheduled_jobs')
    op.drop_index('scheduled_jobs_command_index', table_name='scheduled_jobs')
    op.drop_index('scheduled_jobs_is_enabled_index', table_name='scheduled_jobs')
    op.drop_index('scheduled_jobs_next_run_at_index', table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    op.drop_index('departments_is_active_index', table_name='departments')
    op.drop_table('departments')
    op.drop_index('system_patch_approvals_created_at_index', table_name='system_patch_approvals')
    op.drop_index('system_patch_approvals_patch_type_index', table_name='system_patch_approvals')
    op.drop_index('system_patch_approvals_status_index', table_name='system_patch_approvals')
    op.drop_table('system_patch_approvals')
    op.drop_table('user_onboardings')
    op.drop_index('system_health_logs_created_at_index', table_name='system_health_logs')
    op.drop_index('system_health_logs_overall_status_index', table_name='system_health_logs')
    op.drop_table('system_health_logs')
    op.drop_index('payroll_execution_histories_executed_at_index', table_name='payroll_execution_histories')
    op.drop_index('payroll_execution_histories_executed_at_status_index', table_name='payroll_execution_histories')
    op.drop_index('payroll_execution_histories_job_type_index', table_name='payroll_execution_histories')
    op.drop_index('payroll_execution_histories_job_type_status_index', table_name='payroll_execution_histories')
    op.drop_index('payroll_execution_histories_status_index', table_name='payroll_execution_histories')
    op.drop_table('payroll_execution_histories')
    op.drop_table('password_reset_tokens')
    op.drop_table('cache_locks')
    op.drop_index('application_incidents_assigned_to_index', table_name='application_incidents')
    op.drop_index('application_incidents_detected_at_index', table_name='application_incidents')
    op.drop_index('application_incidents_severity_status_index', table_name='application_incidents')
    op.drop_table('application_incidents')
    op.drop_table('profiles')
    op.drop_index('sessions_last_activity_index', table_name='sessions')
    op.drop_index('sessions_user_id_index', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('system_backup_logs_backup_type_status_index', table_name='system_backup_logs')
    op.drop_index('system_backup_logs_created_at_index', table_name='system_backup_logs')
    op.drop_index('system_backup_logs_status_index', table_name='system_backup_logs')
    op.drop_table('system_backup_logs')
    op.drop_index('model_has_roles_model_id_model_type_index', table_name='model_has_roles')
    op.drop_table('model_has_roles')
    op.drop_index('application_patches_deployed_at_index', table_name='application_patches')
    op.drop_index('application_patches_scheduled_at_index', table_name='application_patches')
    op.drop_index('application_patches_status_index', table_name='application_patches')
    op.drop_table('application_patches')
    op.drop_table('roles')
    op.drop_table('onboarding_skips')
    op.drop_index('security_policies_category_index', table_name='security_policies')
    op.drop_table('security_policies')
    op.drop_index('ip_rules_expires_at_index', table_name='ip_rules')
    op.drop_index('ip_rules_is_active_index', table_name='ip_rules')
    op.drop_index('ip_rules_rule_type_index', table_name='ip_rules')
    op.drop_table('ip_rules')
    op.alter_column('rfid_card_mappings', 'employee_id',
               existing_type=sa.BIGINT(),
               comment='Foreign key to employees table (constraint to be added after Laravel migration)',
               existing_comment='Foreign key to employees table (constraint added separately)',
               existing_nullable=False)
    op.drop_index('ix_rfid_card_mappings_last_used_at', table_name='rfid_card_mappings')
    op.drop_index('uk_employee_active', table_name='rfid_card_mappings', postgresql_where='(is_active = true)')
    op.alter_column('rfid_ledger', 'sequence_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_comment='Auto-increment sequence for hash chain ordering',
               existing_nullable=False)
    op.drop_index('ix_rfid_ledger_scan_timestamp', table_name='rfid_ledger')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_rfid_ledger_scan_timestamp', 'rfid_ledger', ['scan_timestamp'], unique=False)
    op.alter_column('rfid_ledger', 'sequence_id',
               existing_type=sa.BIGINT(),
               server_default=sa.text("nextval('rfid_ledger_sequence_seq'::regclass)"),
               existing_comment='Auto-increment sequence for hash chain ordering',
               existing_nullable=False)
    op.create_index('uk_employee_active', 'rfid_card_mappings', ['employee_id'], unique=True, postgresql_where='(is_active = true)')
    op.create_index('ix_rfid_card_mappings_last_used_at', 'rfid_card_mappings', ['last_used_at'], unique=False)
    op.alter_column('rfid_card_mappings', 'employee_id',
               existing_type=sa.BIGINT(),
               comment='Foreign key to employees table (constraint added separately)',
               existing_comment='Foreign key to employees table (constraint to be added after Laravel migration)',
               existing_nullable=False)
    op.create_table('ip_rules',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ip_address_or_range', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('rule_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='ip_rules_created_by_foreign', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='ip_rules_updated_by_foreign', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='ip_rules_pkey')
    )
    op.create_index('ip_rules_rule_type_index', 'ip_rules', ['rule_type'], unique=False)
    op.create_index('ip_rules_is_active_index', 'ip_rules', ['is_active'], unique=False)
    op.create_index('ip_rules_expires_at_index', 'ip_rules', ['expires_at'], unique=False)
    op.create_table('security_policies',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('policy_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('policy_value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('policy_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='security_policies_pkey'),
    sa.UniqueConstraint('policy_key', name='security_policies_policy_key_unique')
    )
    op.create_index('security_policies_category_index', 'security_policies', ['category'], unique=False)
    op.create_table('onboarding_skips',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('skipped_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('scope', sa.VARCHAR(length=255), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=False),
    sa.Column('system_onboarding_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_onboarding_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("scope::text = ANY (ARRAY['system'::character varying, 'user'::character varying]::text[])", name='onboarding_skips_scope_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='onboarding_skips_user_id_foreign', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='onboarding_skips_pkey')
    )
    op.create_table('roles',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('roles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('guard_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    sa.UniqueConstraint('name', 'guard_name', name='roles_name_guard_name_unique'),
    postgresql_ignore_search_path=False
    )
    op.create_table('application_patches',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('version', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('patch_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=255), server_default=sa.text("'bugfix'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('release_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('deployed_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('failed_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('deployed_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('deployment_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('affected_components', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'scheduled'::character varying, 'deployed'::character varying, 'failed'::character varying, 'rolled_back'::character varying]::text[])", name='application_patches_status_check'),
    sa.CheckConstraint("type::text = ANY (ARRAY['security'::character varying, 'feature'::character varying, 'bugfix'::character varying, 'maintenance'::character varying]::text[])", name='application_patches_type_check'),
    sa.ForeignKeyConstraint(['deployed_by'], ['users.id'], name='application_patches_deployed_by_foreign', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='application_patches_pkey')
    )
    op.create_index('application_patches_status_index', 'application_patches', ['status'], unique=False)
    op.create_index('application_patches_scheduled_at_index', 'application_patches', ['scheduled_at'], unique=False)
    op.create_index('application_patches_deployed_at_index', 'application_patches', ['deployed_at'], unique=False)
    op.create_table('model_has_roles',
    sa.Column('role_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('model_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('model_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='model_has_roles_role_id_foreign', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'model_id', 'model_type', name='model_has_roles_pkey')
    )
    op.create_index('model_has_roles_model_id_model_type_index', 'model_has_roles', ['model_id', 'model_type'], unique=False)
    op.create_table('system_backup_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('backup_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('size_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='system_backup_logs_pkey')
    )
    op.create_index('system_backup_logs_status_index', 'system_backup_logs', ['status'], unique=False)
    op.create_index('system_backup_logs_created_at_index', 'system_backup_logs', ['created_at'], unique=False)
    op.create_index('system_backup_logs_backup_type_status_index', 'system_backup_logs', ['backup_type', 'status'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('last_activity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey')
    )
    op.create_index('sessions_user_id_index', 'sessions', ['user_id'], unique=False)
    op.create_index('sessions_last_activity_index', 'sessions', ['last_activity'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('middle_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('contact_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('emergency_contact', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='profiles_user_id_foreign', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='profiles_pkey'),
    sa.UniqueConstraint('user_id', name='profiles_user_id_unique')
    )
    op.create_table('application_incidents',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=255), server_default=sa.text("'minor'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False),
    sa.Column('reported_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('acknowledged_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('investigating_started_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('closed_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.CheckConstraint("severity::text = ANY (ARRAY['critical'::character varying, 'major'::character varying, 'minor'::character varying]::text[])", name='application_incidents_severity_check'),
    sa.CheckConstraint("status::text = ANY (ARRAY['open'::character varying, 'investigating'::character varying, 'resolved'::character varying, 'closed'::character varying]::text[])", name='application_incidents_status_check'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name='application_incidents_assigned_to_foreign', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], name='application_incidents_reported_by_foreign', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='application_incidents_pkey')
    )
    op.create_index('application_incidents_severity_status_index', 'application_incidents', ['severity', 'status'], unique=False)
    op.create_index('application_incidents_detected_at_index', 'application_incidents', ['detected_at'], unique=False)
    op.create_index('application_incidents_assigned_to_index', 'application_incidents', ['assigned_to'], unique=False)
    op.create_table('cache_locks',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('owner', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expiration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name='cache_locks_pkey')
    )
    op.create_table('password_reset_tokens',
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('email', name='password_reset_tokens_pkey')
    )
    op.create_table('payroll_execution_histories',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Type of payroll job (e.g., payroll_generation, payment_batch)'),
    sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Job status: pending, processing, completed, failed'),
    sa.Column('executed_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=False, comment='When the job started'),
    sa.Column('completed_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True, comment='When the job completed'),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Job-specific metadata (employees_processed, total_amount, error details, etc.)'),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='payroll_execution_histories_pkey')
    )
    op.create_index('payroll_execution_histories_status_index', 'payroll_execution_histories', ['status'], unique=False)
    op.create_index('payroll_execution_histories_job_type_status_index', 'payroll_execution_histories', ['job_type', 'status'], unique=False)
    op.create_index('payroll_execution_histories_job_type_index', 'payroll_execution_histories', ['job_type'], unique=False)
    op.create_index('payroll_execution_histories_executed_at_status_index', 'payroll_execution_histories', ['executed_at', 'status'], unique=False)
    op.create_index('payroll_execution_histories_executed_at_index', 'payroll_execution_histories', ['executed_at'], unique=False)
    op.create_table('system_health_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('cpu_usage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('memory_usage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('disk_usage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('load_average', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('uptime_seconds', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('database_response_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cache_status', sa.VARCHAR(length=255), server_default=sa.text("'unknown'::character varying"), autoincrement=False, nullable=False),
    sa.Column('queue_pending', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('queue_failed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('overall_status', sa.VARCHAR(length=255), server_default=sa.text("'healthy'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='system_health_logs_pkey')
    )
    op.create_index('system_health_logs_overall_status_index', 'system_health_logs', ['overall_status'], unique=False)
    op.create_index('system_health_logs_created_at_index', 'system_health_logs', ['created_at'], unique=False)
    op.create_table('user_onboardings',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('skipped_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('skipped_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('checklist_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'skipped'::character varying]::text[])", name='user_onboardings_status_check'),
    sa.ForeignKeyConstraint(['skipped_by'], ['users.id'], name='user_onboardings_skipped_by_foreign', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_onboardings_user_id_foreign', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_onboardings_pkey')
    )
    op.create_table('system_patch_approvals',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('patch_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('patch_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('version_from', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('version_to', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('requested_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('deployed_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('deployment_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name='system_patch_approvals_approved_by_foreign', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name='system_patch_approvals_requested_by_foreign', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='system_patch_approvals_pkey')
    )
    op.create_index('system_patch_approvals_status_index', 'system_patch_approvals', ['status'], unique=False)
    op.create_index('system_patch_approvals_patch_type_index', 'system_patch_approvals', ['patch_type'], unique=False)
    op.create_index('system_patch_approvals_created_at_index', 'system_patch_approvals', ['created_at'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('manager_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='departments_pkey'),
    sa.UniqueConstraint('code', name='departments_code_unique')
    )
    op.create_index('departments_is_active_index', 'departments', ['is_active'], unique=False)
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Human-readable job name'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Job description/purpose'),
    sa.Column('command', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Laravel Artisan command signature'),
    sa.Column('cron_expression', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Cron expression (e.g., "0 0 * * *")'),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False, comment='Whether job is active'),
    sa.Column('last_run_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True, comment='Last execution timestamp'),
    sa.Column('next_run_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True, comment='Calculated next run time'),
    sa.Column('last_exit_code', sa.INTEGER(), autoincrement=False, nullable=True, comment='Exit code from last run (0 = success)'),
    sa.Column('last_output', sa.TEXT(), autoincrement=False, nullable=True, comment='Output/logs from last execution'),
    sa.Column('run_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='Total executions'),
    sa.Column('success_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='Successful executions'),
    sa.Column('failure_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='Failed executions'),
    sa.Column('created_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='scheduled_jobs_created_by_foreign', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='scheduled_jobs_updated_by_foreign', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='scheduled_jobs_pkey'),
    sa.UniqueConstraint('name', name='scheduled_jobs_name_unique')
    )
    op.create_index('scheduled_jobs_next_run_at_index', 'scheduled_jobs', ['next_run_at'], unique=False)
    op.create_index('scheduled_jobs_is_enabled_index', 'scheduled_jobs', ['is_enabled'], unique=False)
    op.create_index('scheduled_jobs_command_index', 'scheduled_jobs', ['command'], unique=False)
    op.create_index('enabled_next_run_idx', 'scheduled_jobs', ['is_enabled', 'next_run_at'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('queue', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('reserved_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('available_at', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='jobs_pkey')
    )
    op.create_index('jobs_queue_index', 'jobs', ['queue'], unique=False)
    op.create_table('job_batches',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('total_jobs', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pending_jobs', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_jobs', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_job_ids', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('options', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cancelled_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('finished_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='job_batches_pkey')
    )
    op.create_table('system_onboarding',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('skipped_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('skipped_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('checklist_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'skipped'::character varying]::text[])", name='system_onboarding_status_check'),
    sa.ForeignKeyConstraint(['skipped_by'], ['users.id'], name='system_onboarding_skipped_by_foreign', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='system_onboarding_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email_verified_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('remember_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('two_factor_secret', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('two_factor_recovery_codes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('two_factor_confirmed_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_unique'),
    sa.UniqueConstraint('username', name='users_username_unique'),
    postgresql_ignore_search_path=False
    )
    op.create_table('model_has_permissions',
    sa.Column('permission_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('model_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('model_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='model_has_permissions_permission_id_foreign', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permission_id', 'model_id', 'model_type', name='model_has_permissions_pkey')
    )
    op.create_index('model_has_permissions_model_id_model_type_index', 'model_has_permissions', ['model_id', 'model_type'], unique=False)
    op.create_table('cache',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expiration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name='cache_pkey')
    )
    op.create_table('application_uptime_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('checked_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=False),
    sa.Column('is_healthy', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('check_type', sa.VARCHAR(length=255), server_default=sa.text("'automated'::character varying"), autoincrement=False, nullable=False),
    sa.Column('failure_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='application_uptime_logs_pkey')
    )
    op.create_index('application_uptime_logs_is_healthy_checked_at_index', 'application_uptime_logs', ['is_healthy', 'checked_at'], unique=False)
    op.create_index('application_uptime_logs_checked_at_index', 'application_uptime_logs', ['checked_at'], unique=False)
    op.create_table('role_has_permissions',
    sa.Column('permission_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='role_has_permissions_permission_id_foreign', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='role_has_permissions_role_id_foreign', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permission_id', 'role_id', name='role_has_permissions_pkey')
    )
    op.create_table('role_templates',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('template_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='role_templates_pkey'),
    sa.UniqueConstraint('name', name='role_templates_name_unique')
    )
    op.create_table('permissions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('guard_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='permissions_pkey'),
    sa.UniqueConstraint('name', 'guard_name', name='permissions_name_guard_name_unique')
    )
    op.create_table('migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('migration', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('batch', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='migrations_pkey')
    )
    op.create_table('timesheets',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('clock_in', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('clock_out', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('regular_hours', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('overtime_hours', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), server_default=sa.text("'present'::character varying"), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['present'::character varying, 'absent'::character varying, 'late'::character varying, 'on_leave'::character varying]::text[])", name='timesheets_status_check'),
    sa.PrimaryKeyConstraint('id', name='timesheets_pkey'),
    sa.UniqueConstraint('employee_id', 'date', name='timesheets_employee_id_date_unique')
    )
    op.create_index('timesheets_date_status_index', 'timesheets', ['date', 'status'], unique=False)
    op.create_table('failed_jobs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('connection', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('queue', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('exception', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('failed_at', postgresql.TIMESTAMP(precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='failed_jobs_pkey'),
    sa.UniqueConstraint('uuid', name='failed_jobs_uuid_unique')
    )
    op.create_table('security_audit_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=255), server_default=sa.text("'info'::character varying"), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='security_audit_logs_user_id_foreign', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='security_audit_logs_pkey')
    )
    op.create_index('security_audit_logs_user_id_index', 'security_audit_logs', ['user_id'], unique=False)
    op.create_index('security_audit_logs_severity_index', 'security_audit_logs', ['severity'], unique=False)
    op.create_index('security_audit_logs_event_type_index', 'security_audit_logs', ['event_type'], unique=False)
    op.create_index('security_audit_logs_created_at_index', 'security_audit_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###
