<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class PayrollException extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'employee_payroll_calculation_id',
        'payroll_period_id',
        'employee_id',
        'exception_type',
        'severity',
        'title',
        'description',
        'details',
        'current_value',
        'expected_value',
        'variance',
        'variance_percentage',
        'status',
        'resolution_notes',
        'resolved_at',
        'resolved_by',
        'is_auto_generated',
        'detection_rule',
    ];

    protected $casts = [
        'details' => 'array',
        'current_value' => 'decimal:2',
        'expected_value' => 'decimal:2',
        'variance' => 'decimal:2',
        'variance_percentage' => 'decimal:2',
        'resolved_at' => 'datetime',
        'is_auto_generated' => 'boolean',
    ];

    // ============================================================
    // Relationships
    // ============================================================

    public function employeePayrollCalculation(): BelongsTo
    {
        return $this->belongsTo(EmployeePayrollCalculation::class);
    }

    public function payrollPeriod(): BelongsTo
    {
        return $this->belongsTo(PayrollPeriod::class);
    }

    public function employee(): BelongsTo
    {
        return $this->belongsTo(Employee::class);
    }

    public function resolvedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'resolved_by');
    }

    // ============================================================
    // Scopes
    // ============================================================

    public function scopeOpen($query)
    {
        return $query->where('status', 'open');
    }

    public function scopeAcknowledged($query)
    {
        return $query->where('status', 'acknowledged');
    }

    public function scopeResolved($query)
    {
        return $query->where('status', 'resolved');
    }

    public function scopeIgnored($query)
    {
        return $query->where('status', 'ignored');
    }

    public function scopeCritical($query)
    {
        return $query->where('severity', 'critical');
    }

    public function scopeHigh($query)
    {
        return $query->where('severity', 'high');
    }

    public function scopeMedium($query)
    {
        return $query->where('severity', 'medium');
    }

    public function scopeLow($query)
    {
        return $query->where('severity', 'low');
    }

    public function scopeByType($query, string $type)
    {
        return $query->where('exception_type', $type);
    }

    public function scopeBySeverity($query, string $severity)
    {
        return $query->where('severity', $severity);
    }

    public function scopeByPeriod($query, int $periodId)
    {
        return $query->where('payroll_period_id', $periodId);
    }

    public function scopeByEmployee($query, int $employeeId)
    {
        return $query->where('employee_id', $employeeId);
    }

    public function scopeAutoGenerated($query)
    {
        return $query->where('is_auto_generated', true);
    }

    public function scopeManual($query)
    {
        return $query->where('is_auto_generated', false);
    }

    // ============================================================
    // Helper Methods
    // ============================================================

    public function isOpen(): bool
    {
        return $this->status === 'open';
    }

    public function isAcknowledged(): bool
    {
        return $this->status === 'acknowledged';
    }

    public function isResolved(): bool
    {
        return $this->status === 'resolved';
    }

    public function isIgnored(): bool
    {
        return $this->status === 'ignored';
    }

    public function isCritical(): bool
    {
        return $this->severity === 'critical';
    }

    public function isHigh(): bool
    {
        return $this->severity === 'high';
    }

    public function isMedium(): bool
    {
        return $this->severity === 'medium';
    }

    public function isLow(): bool
    {
        return $this->severity === 'low';
    }

    public function canResolve(): bool
    {
        return $this->status === 'open';
    }

    public function canAcknowledge(): bool
    {
        return $this->status === 'open';
    }

    public function canIgnore(): bool
    {
        return $this->status === 'open';
    }

    public function acknowledge(User $user, ?string $notes = null): void
    {
        $this->update([
            'status' => 'acknowledged',
            'resolution_notes' => $notes,
            'resolved_at' => now(),
            'resolved_by' => $user->id,
        ]);
    }

    public function resolve(User $user, string $notes): void
    {
        $this->update([
            'status' => 'resolved',
            'resolution_notes' => $notes,
            'resolved_at' => now(),
            'resolved_by' => $user->id,
        ]);
    }

    public function ignore(User $user, ?string $notes = null): void
    {
        $this->update([
            'status' => 'ignored',
            'resolution_notes' => $notes,
            'resolved_at' => now(),
            'resolved_by' => $user->id,
        ]);
    }

    public function getSeverityColor(): string
    {
        return match ($this->severity) {
            'critical' => 'red',
            'high' => 'orange',
            'medium' => 'yellow',
            'low' => 'blue',
            default => 'gray',
        };
    }

    public function getSeverityIcon(): string
    {
        return match ($this->severity) {
            'critical' => 'alert-triangle',
            'high' => 'alert-circle',
            'medium' => 'info',
            'low' => 'help-circle',
            default => 'circle',
        };
    }

    public function getStatusColor(): string
    {
        return match ($this->status) {
            'open' => 'red',
            'acknowledged' => 'yellow',
            'resolved' => 'green',
            'ignored' => 'gray',
            default => 'gray',
        };
    }

    public function requiresImmediateAction(): bool
    {
        return $this->isOpen() && in_array($this->severity, ['critical', 'high']);
    }

    public function getVariancePercentageFormatted(): string
    {
        if (!$this->variance_percentage) {
            return 'N/A';
        }

        $percentage = (float) $this->variance_percentage;
        $sign = $percentage >= 0 ? '+' : '';
        
        return $sign . number_format($percentage, 2) . '%';
    }
}
